/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Case, HearingSession } from '../types';

/**
 * Converts Arabic-Indic numerals (e.g., ٠١٢٣٤٥٦٧٨٩) to standard Western Arabic numerals (0-9).
 */
export function convertArabicIndicDigits(str: string): string {
  const map: { [key: string]: string } = {
    '٠': '0', '١': '1', '٢': '2', '٣': '3', '٤': '4',
    '٥': '5', '٦': '6', '٧': '7', '٨': '8', '٩': '9'
  };
  return str.replace(/[٠-٩]/g, (d) => map[d] || d);
}

/**
 * Normalizes any date string (with Arabic-Indic numerals, slashes, or dashes) to standard Western YYYY-MM-DD.
 */
export function normalizeHearingDate(d?: string): string {
  if (!d) return '';
  const clean = convertArabicIndicDigits(d.trim()).replace(/\//g, '-');
  const parts = clean.split('-');
  if (parts.length === 3) {
    const y = parts[0].padStart(4, '20');
    const m = parts[1].padStart(2, '0');
    const day = parts[2].padStart(2, '0');
    return `${y}-${m}-${day}`;
  }
  return clean;
}

/**
 * Scans a string for date patterns and returns them in YYYY-MM-DD format if found.
 * Supports:
 * - YYYY-MM-DD or YYYY/MM/DD
 * - DD-MM-YYYY or DD/MM/YYYY
 * - DD-MM or DD/MM (uses current year)
 */
export function extractHearingDate(text: string): string | null {
  if (!text) return null;
  
  const cleanText = convertArabicIndicDigits(text);
  
  // 1. Match YYYY-MM-DD or YYYY/MM/DD
  const ymdRegex = /(?:^|[^0-9])(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})(?:$|[^0-9])/;
  const ymdMatch = cleanText.match(ymdRegex);
  if (ymdMatch) {
    const year = parseInt(ymdMatch[1], 10);
    const month = parseInt(ymdMatch[2], 10);
    const day = parseInt(ymdMatch[3], 10);
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    }
  }

  // 2. Match DD-MM-YYYY or DD/MM/YYYY
  const dmyRegex = /(?:^|[^0-9])(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})(?:$|[^0-9])/;
  const dmyMatch = cleanText.match(dmyRegex);
  if (dmyMatch) {
    const day = parseInt(dmyMatch[1], 10);
    const month = parseInt(dmyMatch[2], 10);
    const year = parseInt(dmyMatch[3], 10);
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    }
  }

  // 3. Match DD-MM or DD/MM (without year, fallback to current year)
  const dmRegex = /(?:^|[^0-9])(\d{1,2})[-/.](\d{1,2})(?:$|[^0-9])/;
  const dmMatch = cleanText.match(dmRegex);
  if (dmMatch) {
    const day = parseInt(dmMatch[1], 10);
    const month = parseInt(dmMatch[2], 10);
    const year = new Date().getFullYear();
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      // Ensure we don't accidentally match something like 15-05 in "Case 15-05" unless it's likely a date
      // We can check if the surrounding context contains calendar words
      const dateIndicatorKeywords = ['جلسة', 'تاريخ', 'يوم', 'جلسه', 'شهر', 'عام'];
      const hasIndicator = dateIndicatorKeywords.some(kw => (text || '').includes(kw));
      if (hasIndicator) {
        return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
      }
    }
  }

  return null;
}

/**
 * Checks if a case has been referred to court (محالة للمحكمة / محالة للمحاكمة الجنائية).
 */
export function isCaseReferredToCourt(c?: Partial<Case> | null): boolean {
  if (!c) return false;
  if ((c as any).isReferredToCourt === true) return true;
  const s = (c.status || '').trim();
  const defStatus = ((c as any).investigationDefendantStatus || '').trim();
  const keywords = [
    'محالة للمحكمة',
    'محالة للمحاكمة',
    'محالة للمحاكمة الجنائية',
    'تمت الإحالة للمحكمة',
    'تمت الإحالة للمحاكمة',
    'إحالة للمحكمة',
    'إحالة للمحاكمة'
  ];
  return keywords.some(kw => s.includes(kw) || defStatus.includes(kw));
}

/**
 * Checks if a file name or category suggests it relates to a court hearing session.
 */
export function isAutoGeneratedSessionId(id: string): boolean {
  return (
    id.startsWith('session-court-') ||
    id.startsWith('session-expert-') ||
    id.startsWith('session-expert-next-') ||
    id.startsWith('session-detention-') ||
    id.startsWith('session-proc-') ||
    id.startsWith('session-file-') ||
    id.startsWith('session-sync-expert-') ||
    id.startsWith('session-detention-next-') ||
    id.startsWith('session-detention-prev-') ||
    id.startsWith('session-next-')
  );
}

/**
 * Generates a deterministic, collision-proof session ID for detention renewal hearings.
 * Enforces: caseId + normalized date + detention type.
 */
export function getDetentionSessionId(caseId: string, date: string): string {
  const norm = normalizeHearingDate(date);
  return `session-detention-${caseId}-${norm}`;
}

/**
 * Categorizes a session into 'expert', 'detention', or court/regular case type.
 */
export function getSessionCategory(s: Partial<HearingSession>, parentCase?: Case | null): string {
  if (!s) return parentCase?.type || 'court';

  const isExp = !!(
    s.isExpertSession ||
    (s.id && s.id.includes('expert')) ||
    (s.court && (s.court.includes('خبراء') || s.court.includes('خبير'))) ||
    (s.subject && (s.subject.includes('خبراء') || s.subject.includes('خبير') || s.subject.includes('خبرة'))) ||
    parentCase?.isReferredToExperts ||
    parentCase?.expertReferral?.isReferred
  );
  if (isExp) return 'expert';

  const isDet = !!(
    s.isDetentionRenewal ||
    (s.id && s.id.includes('detention')) ||
    (s.court && (s.court.includes('تجديد') || s.court.includes('مشورة'))) ||
    (s.subject && (s.subject.includes('تجديد') || s.subject.includes('حبس') || s.subject.includes('احتياطي'))) ||
    parentCase?.isInvestigationActive
  );
  if (isDet) return 'detention';

  return (s.type || parentCase?.type || 'court').trim();
}

/**
 * Normalizes case number for consistent matching and deduplication:
 * - converts Eastern Arabic digits to Western digits
 * - removes all extra spaces and slashes formatting
 */
export function normalizeCaseNumber(caseNum?: string): string {
  if (!caseNum) return '';
  const clean = convertArabicIndicDigits(caseNum.trim());
  return clean.replace(/\s+/g, '').replace(/[\\/]/g, '/');
}

/**
 * Normalizes opponent name for robust deduplication and matching:
 * - strips punctuation, extra spaces, honorifics (السيد / الأستاذ / شركة / ضد)
 * - unifies Arabic letter variants (أ, إ, آ -> ا), (ى -> ي), (ة -> ه)
 * - converts Eastern Arabic digits
 */
export function normalizeOpponentName(name?: string): string {
  if (!name) return '';
  let clean = convertArabicIndicDigits(name.trim().toLowerCase());
  // Remove common prefixes or noise words that might vary in manual entry
  clean = clean.replace(/^(ضد|الخصم|السيد|السيدة|الأستاذ|الاستاذ|شركة|مؤسسة)\s+/g, '');
  // Normalize Alef forms
  clean = clean.replace(/[إأآا]/g, 'ا');
  // Normalize Yaa / Alef Maksura
  clean = clean.replace(/[يى]/g, 'ي');
  // Normalize Taa Marbuta / Haa
  clean = clean.replace(/[ةه]/g, 'ه');
  // Remove Arabic diacritics / tashkeel
  clean = clean.replace(/[\u064B-\u065F\u0670]/g, '');
  // Remove all non-alphanumeric characters (including symbols, punctuation, dashes, quotes)
  clean = clean.replace(/[^\w\d\u0600-\u06FF]/g, '');
  return clean;
}

/**
 * Checks if two opponent names match or one contains the other.
 */
export function isOpponentMatch(opp1?: string, opp2?: string): boolean {
  const n1 = normalizeOpponentName(opp1);
  const n2 = normalizeOpponentName(opp2);
  if (!n1 || !n2) return true; // If one is unspecified, do not block match
  return n1 === n2 || n1.includes(n2) || n2.includes(n1);
}

/**
 * Checks if two sessions represent the exact same session based strictly on
 * (Case Number + Opponents + Session Date).
 */
export function isSameSession(s1: Partial<HearingSession>, s2: Partial<HearingSession>, cases?: Case[]): boolean {
  if (!s1 || !s2) return false;
  if (s1.id && s2.id && s1.id === s2.id) return true;

  // 1. Session Date matching
  const date1 = normalizeHearingDate(s1.date);
  const date2 = normalizeHearingDate(s2.date);
  if (!date1 || !date2 || date1 !== date2) return false;

  const c1 = cases?.find(c => c.id === s1.caseId);
  const c2 = cases?.find(c => c.id === s2.caseId);

  // 2. Case Number matching
  const num1 = normalizeCaseNumber(s1.caseNumber || c1?.caseNumberFirstInstance || c1?.investigationNumber);
  const num2 = normalizeCaseNumber(s2.caseNumber || c2?.caseNumberFirstInstance || c2?.investigationNumber);
  const isCaseIdMatch = !!(s1.caseId && s2.caseId && s1.caseId === s2.caseId) || !!(c1 && c2 && c1.id === c2.id);
  const isCaseNumMatch = !!(num1 && num2 && num1 === num2);

  if (!isCaseIdMatch && !isCaseNumMatch) return false;

  // 3. Opponents matching
  const opp1 = s1.opponentName || c1?.opponent?.name;
  const opp2 = s2.opponentName || c2?.opponent?.name;
  if (!isOpponentMatch(opp1, opp2)) return false;

  return true;
}

/**
 * Finds an existing session matching an incoming session by:
 * (Case Number + Opponents + Session Date).
 * Matches existing records so incoming sessions update the existing record
 * instead of creating duplicate records for the same case, opponents, and date.
 */
export function findMatchingSession(
  existingSessions: HearingSession[], 
  target: Partial<HearingSession>, 
  parentCase?: Case | null,
  cases?: Case[]
): HearingSession | undefined {
  if (!target) return undefined;
  
  // 1. Direct ID match
  if (target.id) {
    const direct = existingSessions.find(s => s.id === target.id);
    if (direct) return direct;
  }

  const targetDate = normalizeHearingDate(target.date);
  if (!targetDate) return undefined;

  const pCase = parentCase || cases?.find(c => c.id === target.caseId);
  const targetCaseId = target.caseId || pCase?.id;
  const targetCaseNum = normalizeCaseNumber(target.caseNumber || pCase?.caseNumberFirstInstance || pCase?.investigationNumber);
  const targetCaseYear = target.caseYear || pCase?.caseYearFirstInstance || pCase?.investigationYear;
  const targetOpponent = target.opponentName || pCase?.opponent?.name;

  return existingSessions.find(s => {
    // 1. Check Date (must match exactly)
    if (normalizeHearingDate(s.date) !== targetDate) return false;

    // 2. Check Case Number (Case ID OR normalized Case Number + Year)
    const sCase = (targetCaseId && s.caseId === targetCaseId)
      ? pCase
      : cases?.find(c => c.id === s.caseId);

    const sCaseNum = normalizeCaseNumber(s.caseNumber || sCase?.caseNumberFirstInstance || sCase?.investigationNumber);
    const sCaseYear = s.caseYear || sCase?.caseYearFirstInstance || sCase?.investigationYear;

    const isSameCase = 
      (targetCaseId && s.caseId && s.caseId === targetCaseId) ||
      (targetCaseNum && sCaseNum && targetCaseNum === sCaseNum && (!targetCaseYear || !sCaseYear || targetCaseYear === sCaseYear));
    if (!isSameCase) return false;

    // 3. Check Opponents (opponentName)
    const sOpponent = s.opponentName || sCase?.opponent?.name;
    if (!isOpponentMatch(targetOpponent, sOpponent)) return false;

    return true;
  });
}

/**
 * Merges incoming session updates into an existing session while preserving original session ID,
 * history, decisions, notes, and requirements.
 */
export function mergeSessionData(existing: HearingSession, incoming: Partial<HearingSession>): HearingSession {
  const normIncomingDate = normalizeHearingDate(incoming.date);
  const normIncomingNextDate = normalizeHearingDate(incoming.nextHearingDate);
  const normExistingDate = normalizeHearingDate(existing.date);
  const normExistingNextDate = normalizeHearingDate(existing.nextHearingDate);

  const existingHasDecision = (!!existing.decision && existing.decision.trim() !== '') || existing.status === 'completed';
  const incomingHasDecision = incoming.decision !== undefined && incoming.decision !== null && incoming.decision.trim() !== '';

  const finalDecision = incomingHasDecision 
    ? incoming.decision!.trim() 
    : (existingHasDecision ? existing.decision : undefined);

  // CRITICAL: A completed session with a recorded decision must NEVER be reverted back to pending!
  const finalStatus: HearingSession['status'] = incomingHasDecision
    ? (incoming.status === 'postponed' ? 'postponed' : 'completed')
    : existingHasDecision
    ? (existing.status === 'postponed' ? 'postponed' : 'completed')
    : (incoming.status || existing.status || 'pending');

  return {
    ...existing,
    ...incoming,
    id: existing.id, // ALWAYS preserve the original ID!
    caseId: existing.caseId || incoming.caseId || '',
    caseNumber: existing.caseNumber || incoming.caseNumber || '',
    caseYear: existing.caseYear || incoming.caseYear || '',
    clientName: incoming.clientName || existing.clientName || '',
    opponentName: incoming.opponentName || existing.opponentName || 'غير محدد',
    date: normIncomingDate || normExistingDate,
    time: incoming.time || existing.time || '09:00',
    court: incoming.court || existing.court || '',
    circuit: incoming.circuit || existing.circuit || '',
    type: incoming.type || existing.type || 'مدني',
    subject: incoming.subject || existing.subject || 'جلسة متداولة ومتابعة',
    decision: finalDecision,
    nextHearingDate: normIncomingNextDate || normExistingNextDate || undefined,
    status: finalStatus,
    whatHappened: incoming.whatHappened || existing.whatHappened,
    requirements: incoming.requirements || existing.requirements,
    rollPhotoUrl: incoming.rollPhotoUrl || existing.rollPhotoUrl,
    notes: incoming.notes || existing.notes,
    assignedLawyerId: incoming.assignedLawyerId || existing.assignedLawyerId,
    assignedLawyerName: incoming.assignedLawyerName || existing.assignedLawyerName,
    isDetentionRenewal: incoming.isDetentionRenewal ?? existing.isDetentionRenewal,
    detentionStartDate: incoming.detentionStartDate || existing.detentionStartDate,
    detentionDurationDays: incoming.detentionDurationDays || existing.detentionDurationDays,
    detentionDuration: incoming.detentionDuration || existing.detentionDuration,
    detentionRenewalNumber: incoming.detentionRenewalNumber || existing.detentionRenewalNumber,
    detentionDecisionNumber: incoming.detentionDecisionNumber || existing.detentionDecisionNumber,
    detentionAuthority: incoming.detentionAuthority || existing.detentionAuthority,
    detentionNextAuthority: incoming.detentionNextAuthority || existing.detentionNextAuthority,
    detentionRenewalId: incoming.detentionRenewalId || existing.detentionRenewalId,
    isExpertSession: incoming.isExpertSession ?? existing.isExpertSession,
    expertSessionId: incoming.expertSessionId || existing.expertSessionId
  };
}

/**
 * Deduplicates an array of sessions strictly based on (Case Number + Opponents + Session Date),
 * merging duplicates into single comprehensive records with all decisions and notes preserved,
 * while allowing multiple sessions for the same case if they have different dates.
 */
export function deduplicateSessions(sessions: HearingSession[], cases?: Case[]): HearingSession[] {
  if (!sessions || sessions.length === 0) return [];

  const map = new Map<string, HearingSession>();

  for (const s of sessions) {
    const normDate = normalizeHearingDate(s.date);
    if (!normDate) continue;

    const parentCase = cases?.find(c => 
      (s.caseId && c.id === s.caseId) || 
      (s.caseNumber && normalizeCaseNumber(c.caseNumberFirstInstance) === normalizeCaseNumber(s.caseNumber) && (!s.caseYear || c.caseYearFirstInstance === s.caseYear)) ||
      (s.caseNumber && normalizeCaseNumber(c.investigationNumber) === normalizeCaseNumber(s.caseNumber))
    );

    const normCaseNum = normalizeCaseNumber(s.caseNumber || parentCase?.caseNumberFirstInstance || parentCase?.investigationNumber || s.caseId);
    const caseYear = s.caseYear || parentCase?.caseYearFirstInstance || parentCase?.investigationYear || '';
    const caseKey = `${normCaseNum}_${caseYear}`;
    const opponentKey = normalizeOpponentName(s.opponentName || parentCase?.opponent?.name || '');
    
    // Deduplication key strictly: Case Number + Opponents + Date
    const dedupeKey = `${caseKey}__${opponentKey}__${normDate}`;

    const existing = map.get(dedupeKey);
    if (!existing) {
      map.set(dedupeKey, { ...s, date: normDate });
    } else {
      const existingHasDecision = (!!existing.decision && existing.decision.trim() !== '') || existing.status === 'completed';
      const sHasDecision = (!!s.decision && s.decision.trim() !== '') || s.status === 'completed';

      // Always prioritize the record that has a decision as the base so it is never lost or overwritten
      if (sHasDecision && !existingHasDecision) {
        const merged = mergeSessionData(s, existing);
        map.set(dedupeKey, merged);
      } else {
        const merged = mergeSessionData(existing, s);
        map.set(dedupeKey, merged);
      }
    }
  }

  return Array.from(map.values());
}

/**
 * Extracts all expected automated hearing sessions from a given case.
 */
export function generateExpectedAutoSessionsForCase(c: Case, users: any[] = []): HearingSession[] {
  const result: HearingSession[] = [];
  if (!c || c.isArchived) return result;

  const assignedLawyerName = users.find(u => u.id === c.assignedLawyerId)?.fullName || undefined;

  // 1. Files scan
  if (c.files && Array.isArray(c.files)) {
    c.files.forEach(file => {
      if (!file || !file.name) return;
      const fileDate = extractHearingDate(file.name);
      if (!fileDate) return;
      const sessionId = `session-file-${c.id}-${file.id || Math.random().toString(36).substr(2, 9)}`;
      result.push({
        id: sessionId,
        caseId: c.id,
        caseNumber: c.caseNumberFirstInstance,
        caseYear: c.caseYearFirstInstance,
        clientName: c.clientName,
        opponentName: c.opponent?.name || (c.opponentsList && c.opponentsList[0]?.name) || 'غير محدد',
        court: c.court || 'غير محدد',
        circuit: c.circuit || 'غير محدد',
        type: c.type,
        date: fileDate,
        time: '09:00',
        subject: `جلسة مستخرجة ومزامنة تلقائياً من مستند: ${file.name}`,
        status: 'pending',
        assignedLawyerId: c.assignedLawyerId || undefined,
        assignedLawyerName,
        notes: `تم رصد الجلسة وإضافتها تلقائياً بناءً على الملف: ${file.name}`
      });
    });
  }

  // 2. Expert sessions scan
  if ((c.isReferredToExperts || c.expertReferral?.isReferred) && c.expertReferral) {
    // 2.1 First session date if specified AND not already included in sessions array
    const hasFirstInSessions = c.expertReferral.firstSessionDate && c.expertReferral.sessions?.some(s => s.date === c.expertReferral?.firstSessionDate);
    if (c.expertReferral.firstSessionDate && !hasFirstInSessions) {
      const firstSessId = `session-expert-first-${c.id}`;
      result.push({
        id: firstSessId,
        caseId: c.id,
        caseNumber: c.caseNumberFirstInstance,
        caseYear: c.caseYearFirstInstance,
        clientName: c.clientName,
        opponentName: c.opponent?.name || 'غير محدد',
        court: c.expertReferral.expertOffice || c.court || 'مكتب خبراء وزارة العدل',
        circuit: c.expertReferral.courtOrCircuit || 'جلسة خبراء أولى',
        type: c.type,
        date: c.expertReferral.firstSessionDate,
        time: '10:00',
        subject: `جلسة خبراء أولى - ${c.expertReferral.expertOffice || 'مكتب الخبراء'} (الخبير: ${c.expertReferral.expertName || 'غير محدد'})`,
        status: 'pending',
        decision: undefined,
        assignedLawyerId: c.assignedLawyerId || undefined,
        assignedLawyerName,
        notes: `جلسة إحالة للخبراء الأولى محددة بالقضية. ${c.expertReferral.referralReason || ''}`,
        isExpertSession: true,
        expertSessionId: 'first-session'
      });
    }

    // 2.2 Sessions array
    if (c.expertReferral.sessions && c.expertReferral.sessions.length > 0) {
      c.expertReferral.sessions.forEach((expSess, idx) => {
        if (expSess.date) {
          const expKey = expSess.id || `exp-${idx}`;
          const sessionId = `session-expert-${c.id}-${expKey}`;
          const hasRealDecision = !!expSess.decisionOrAction && expSess.decisionOrAction.trim() !== '';
          const effectiveStatus = expSess.status === 'pending'
            ? 'pending'
            : expSess.status === 'postponed'
            ? 'postponed'
            : (hasRealDecision || expSess.status === 'completed')
            ? 'completed'
            : 'pending';

          result.push({
            id: sessionId,
            caseId: c.id,
            caseNumber: c.caseNumberFirstInstance,
            caseYear: c.caseYearFirstInstance,
            clientName: c.clientName,
            opponentName: c.opponent?.name || 'غير محدد',
            court: c.expertReferral?.expertOffice || c.court || 'مكتب خبراء وزارة العدل',
            circuit: expSess.location || 'جلسة خبراء',
            type: c.type,
            date: expSess.date,
            time: expSess.time || '10:00',
            subject: `جلسة خبرة (${expSess.sessionType || 'حضور الخبير'}) - ${expSess.location || c.expertReferral?.expertOffice || 'مكتب الخبراء'}`,
            status: effectiveStatus,
            decision: hasRealDecision ? expSess.decisionOrAction : undefined,
            assignedLawyerId: c.assignedLawyerId || undefined,
            assignedLawyerName,
            notes: expSess.notes || 'جلسة خبراء مسجلة في ملف القضية.',
            isExpertSession: true,
            expertSessionId: expKey
          });
        }

        // Next session date if set and distinct from current session date and not already an explicit session item
        if (expSess.nextSessionDate && expSess.nextSessionDate !== expSess.date) {
          const hasNextInArray = c.expertReferral?.sessions?.some(s => s.date === expSess.nextSessionDate);
          if (!hasNextInArray) {
            const nextKey = `session-expert-next-${c.id}-${expSess.id || idx}`;
            result.push({
              id: nextKey,
              caseId: c.id,
              caseNumber: c.caseNumberFirstInstance,
              caseYear: c.caseYearFirstInstance,
              clientName: c.clientName,
              opponentName: c.opponent?.name || 'غير محدد',
              court: c.expertReferral?.expertOffice || 'مكتب خبراء وزارة العدل',
              circuit: expSess.location || c.expertReferral?.courtOrCircuit || 'جلسة مباشرة الخبير',
              type: c.type,
              date: expSess.nextSessionDate,
              time: '10:00',
              subject: `جلسة خبرة ومباشرة قادمة (${expSess.sessionType || 'متابعة'}) - ${expSess.location || c.expertReferral?.expertOffice || 'مكتب الخبراء'}`,
              status: 'pending',
              decision: undefined,
              assignedLawyerId: c.assignedLawyerId || undefined,
              assignedLawyerName,
              notes: `جلسة خبراء مؤجلة بناءً على قرار الجلسة السابقة: ${expSess.decisionOrAction || ''}`,
              isExpertSession: true,
              expertSessionId: `next-${expSess.id || idx}`
            });
          }
        }
      });
    }
  }

  // 3. Detention Renewals scan (سجل تجديدات الحبس الاحتياطي - مشروط حصرياً بتفعيل مرحلة التحقيق)
  if (c.isInvestigationActive && c.detentionRenewals && c.detentionRenewals.length > 0) {
    const isReferred = isCaseReferredToCourt(c);
    const nowLocal = new Date();
    const todayLocalStr = `${nowLocal.getFullYear()}-${String(nowLocal.getMonth() + 1).padStart(2, '0')}-${String(nowLocal.getDate()).padStart(2, '0')}`;

    c.detentionRenewals.forEach((ren, idx) => {
      const renKey = ren.id || `ren-${idx}`;
      const normRenDate = normalizeHearingDate(ren.date || ren.renewalDate);
      const normNextDate = normalizeHearingDate(ren.nextRenewalDate);

      // Check if both dates exist and are different, and that nextRenewalDate isn't already covered by another explicit renewal record
      const isNextDateCovered = !!(normNextDate && c.detentionRenewals!.some(r => (r.id !== renKey) && (normalizeHearingDate(r.date || r.renewalDate) === normNextDate)));
      const hasDistinctNextDate = !!(normNextDate && normRenDate && normNextDate !== normRenDate && !isNextDateCovered);
      const effectiveDate = normRenDate || normNextDate;

      // A. Upcoming detention renewal session (when distinct next date exists)
      // حظر قاطع: لا تُنشئ أي جلسة تجديد حبس جديدة أو قادمة بعد إحالة القضية للمحكمة!
      if (!isReferred && hasDistinctNextDate && normNextDate) {
        const nextSessionId = getDetentionSessionId(c.id, normNextDate);
        result.push({
          id: nextSessionId,
          caseId: c.id,
          caseNumber: c.investigationNumber ? `${c.investigationNumber}/${c.investigationYear || c.caseYearFirstInstance}` : c.caseNumberFirstInstance,
          caseYear: c.investigationYear || c.caseYearFirstInstance,
          clientName: c.clientName,
          opponentName: c.investigationAuthority || (c.opponent?.name || 'النيابة العامة'),
          court: ren.court || ren.nextAuthority || ren.authority || c.investigationAuthority || c.court || 'النيابة العامة / غرفة المشورة',
          circuit: ren.circuit || c.circuit || 'دائرة تجديد الحبس',
          type: c.type || 'جنح',
          date: normNextDate,
          time: '09:00',
          subject: `جلسة تجديد حبس احتياطي (${ren.nextAuthority || ren.authority || 'جهة التجديد'})`,
          status: 'pending',
          assignedLawyerId: c.assignedLawyerId || undefined,
          assignedLawyerName,
          notes: `جلسة تجديد حبس احتياطي قادمة للمتهم/الموكل: ${c.clientName}. ${ren.notes || ''}`,
          isDetentionRenewal: true,
          detentionStartDate: ren.detentionStartDate || c.detentionStartDate,
          detentionAuthority: ren.nextAuthority || ren.authority,
          detentionNextAuthority: ren.nextAuthority,
          detentionDurationDays: ren.durationDays,
          detentionDuration: ren.duration || (ren.durationDays ? `${ren.durationDays} يوم` : undefined),
          detentionRenewalNumber: ren.renewalNumber ? (Number(ren.renewalNumber) + 1) : (idx + 2),
          detentionRenewalId: renKey
        });
      }

      // B. Primary / Recorded renewal session date
      if (effectiveDate) {
        const renSessionId = getDetentionSessionId(c.id, effectiveDate);
        const hasDecision = !!ren.decision && ren.decision.trim() !== '';

        // إذا كانت القضية محالة للمحكمة: حافظ على جميع جلسات تجديد الحبس السابقة كسجل تاريخي للعرض، وامنع الجلسات القادمة غير المبتوت فيها
        if (isReferred && !hasDecision && effectiveDate >= todayLocalStr) {
          return;
        }

        result.push({
          id: renSessionId,
          caseId: c.id,
          caseNumber: c.investigationNumber ? `${c.investigationNumber}/${c.investigationYear || c.caseYearFirstInstance}` : c.caseNumberFirstInstance,
          caseYear: c.investigationYear || c.caseYearFirstInstance,
          clientName: c.clientName,
          opponentName: c.investigationAuthority || (c.opponent?.name || 'النيابة العامة'),
          court: ren.court || ren.authority || c.investigationAuthority || c.court || 'النيابة العامة',
          circuit: ren.circuit || c.circuit || 'دائرة تجديد الحبس',
          type: c.type || 'جنح',
          date: effectiveDate,
          time: '09:00',
          subject: `جلسة تجديد حبس احتياطي (${ren.authority || 'النيابة العامة'})`,
          status: hasDecision ? 'completed' : 'pending',
          decision: hasDecision ? ren.decision.trim() : undefined,
          nextHearingDate: (!isReferred && normNextDate && normNextDate !== effectiveDate) ? normNextDate : undefined,
          assignedLawyerId: c.assignedLawyerId || undefined,
          assignedLawyerName,
          notes: `جلسة تجديد حبس احتياطي مسجلة في ملف القضية. ${ren.notes || ''}`,
          isDetentionRenewal: true,
          detentionStartDate: ren.detentionStartDate || c.detentionStartDate,
          detentionAuthority: ren.authority,
          detentionNextAuthority: ren.nextAuthority,
          detentionDurationDays: ren.durationDays,
          detentionDuration: ren.duration || (ren.durationDays ? `${ren.durationDays} يوم` : undefined),
          detentionRenewalNumber: ren.renewalNumber || (idx + 1),
          detentionDecisionNumber: ren.decisionNumber,
          detentionRenewalId: renKey
        });
      }
    });
  }

  // 4. Investigation Procedures scan (سجل إجراءات التحقيق بالنيابة - يتم إنشاؤها فقط عند تفعيل مرحلة التحقيق)
  if (c.isInvestigationActive && c.investigationProcedures && c.investigationProcedures.length > 0) {
    const isReferred = isCaseReferredToCourt(c);
    const nowLocal = new Date();
    const todayLocalStr = `${nowLocal.getFullYear()}-${String(nowLocal.getMonth() + 1).padStart(2, '0')}-${String(nowLocal.getDate()).padStart(2, '0')}`;

    c.investigationProcedures.forEach((proc, idx) => {
      const normProcDate = normalizeHearingDate(proc.sessionDate);
      if (normProcDate) {
        // Prevent duplicate if an explicit detention renewal record already covers this exact date
        const isCoveredByRenewal = c.detentionRenewals && c.detentionRenewals.some(r => normalizeHearingDate(r.date || r.renewalDate) === normProcDate);
        if (isCoveredByRenewal) return;

        const isDetention = (proc.actionType || '').includes('تجديد') || (proc.actionType || '').includes('حبس') || (proc.actionType || '').includes('استئناف أمر الحبس') || (proc.actionType || '').includes('تحقيق');

        // إذا كانت القضية محالة للمحكمة، لا تُنشئ إجراءات تجديد قادمة بدون قرار
        if (isReferred && isDetention && !proc.decision && normProcDate >= todayLocalStr) {
          return;
        }

        const procKey = proc.id || `proc-${idx}`;
        const procSessionId = isDetention ? getDetentionSessionId(c.id, normProcDate) : `session-proc-${c.id}-${procKey}`;
        result.push({
          id: procSessionId,
          caseId: c.id,
          caseNumber: c.investigationNumber ? `${c.investigationNumber}/${c.investigationYear || c.caseYearFirstInstance}` : c.caseNumberFirstInstance,
          caseYear: c.investigationYear || c.caseYearFirstInstance,
          clientName: c.clientName,
          opponentName: proc.authority || c.investigationAuthority || 'النيابة العامة',
          court: proc.authority || c.court || 'النيابة العامة',
          circuit: c.circuit || 'غرفة المشورة / التحقيق',
          type: c.type || 'جنائي',
          date: normProcDate,
          time: '09:00',
          subject: `جلسة ${proc.actionType || 'تجديد حبس احتياطي'} - ${proc.authority || 'النيابة العامة'}`,
          status: proc.decision ? 'completed' : 'pending',
          decision: proc.decision ? proc.decision.trim() : undefined,
          assignedLawyerId: c.assignedLawyerId || undefined,
          assignedLawyerName,
          notes: `إجراء تحقيق وتجديد حبس مسجل بملف التحقيقات. ${proc.notes || ''}`,
          isDetentionRenewal: isDetention,
          detentionAuthority: proc.authority,
          detentionDurationDays: proc.renewalDays || 15
        });
      }
    });
  }

  // 5. Regular Court Hearing Session (جلسة المحاكمة أو المتابعة المحددة بالقضية)
  if (!c.noUpcomingHearing && c.nextHearingDate) {
    const normNextCourtDate = normalizeHearingDate(c.nextHearingDate);
    if (normNextCourtDate) {
      // Check if a session on this exact date is already generated from detention renewals or expert sessions
      const alreadyHasSessionOnDate = result.some(r => normalizeHearingDate(r.date) === normNextCourtDate);
      if (!alreadyHasSessionOnDate) {
        const isDet = !!(c.isInvestigationActive && !isCaseReferredToCourt(c));
        const opponentDisplayName = c.opponent?.name || 
          (c.opponentsList && c.opponentsList.length > 0 ? c.opponentsList.map(o => o?.name).filter(Boolean).join('، ') : 'الخصم');

        result.push({
          id: isDet ? getDetentionSessionId(c.id, normNextCourtDate) : `session-court-${c.id}-${normNextCourtDate}`,
          caseId: c.id,
          caseNumber: c.caseNumberFirstInstance || c.investigationNumber || 'غير محدد',
          caseYear: c.caseYearFirstInstance || c.investigationYear || '',
          clientName: c.clientName,
          opponentName: opponentDisplayName,
          court: c.court || c.courtFirstInstance || (isDet ? (c.investigationAuthority || 'النيابة العامة') : 'المحكمة المختصة'),
          circuit: c.circuit || c.circuitFirstInstance || (isDet ? 'غرفة المشورة / النيابة' : 'دائرة المحاكمة'),
          type: c.type || (isDet ? 'جنح' : 'جنائي'),
          date: normNextCourtDate,
          time: c.nextHearingTime || '09:00',
          subject: c.nextHearingSubject || (isDet ? 'جلسة تجديد حبس احتياطي' : (isCaseReferredToCourt(c) ? 'جلسة محاكمة أول درجة' : 'جلسة محاكمة')),
          status: 'pending',
          assignedLawyerId: c.assignedLawyerId || undefined,
          assignedLawyerName,
          notes: isDet ? 'جلسة تجديد حبس مسجلة للمتابعة القضائية.' : (isCaseReferredToCourt(c) ? 'جلسة محاكمة عادية مجدولة بعد إحالة القضية للمحكمة.' : 'جلسة محاكمة عادية.'),
          isDetentionRenewal: isDet,
          detentionAuthority: isDet ? (c.investigationAuthority || 'النيابة العامة') : undefined,
          detentionDurationDays: isDet ? 15 : undefined
        });
      }
    }
  }

  return deduplicateSessions(result, [c]);
}

/**
 * Extracts all expected automated hearing sessions from all active cases.
 */
export function generateExpectedAutoSessionsForAllCases(cases: Case[], users: any[] = []): Map<string, HearingSession> {
  const map = new Map<string, HearingSession>();
  if (!cases || cases.length === 0) return map;

  cases.forEach(c => {
    const sessions = generateExpectedAutoSessionsForCase(c, users);
    sessions.forEach(sess => {
      map.set(sess.id, sess);
    });
  });

  return map;
}

/**
 * Checks if a file name or category suggests it relates to a court hearing session.
 */
export function checkIfRelatesToHearing(fileName: string, fileCategory: string): boolean {
  const lowerFileName = (fileName || '').toLowerCase();
  
  // Keywords indicating hearing
  const hearingKeywords = [
    'جلسة', 'جلسه', 'حضور', 'رول', 'محضر', 'مرافعة', 
    'مرافعه', 'مذكرة', 'مذكره', 'دفاع', 'حكم', 'قرار', 'تأجيل', 'أجندة', 'اجندة'
  ];
  
  const hasKeyword = hearingKeywords.some(kw => lowerFileName.includes(kw));
  const isHearingCategory = fileCategory ? ['صحف الدعاوى', 'مذكرات', 'أحكام'].includes(fileCategory) : false;
  
  return hasKeyword || isHearingCategory;
}

/**
 * Generates a pre-filled suggestion for a hearing session based on the file metadata.
 */
export function suggestHearingSession(
  fileName: string, 
  fileCategory: string, 
  currentCase: Case
): {
  isSuggested: boolean;
  session: Omit<HearingSession, 'id'>;
} {
  const isSuggested = checkIfRelatesToHearing(fileName, fileCategory);
  const today = new Date();
  const localDateStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;
  const detectedDate = extractHearingDate(fileName) || currentCase.nextHearingDate || localDateStr;
  
  // Build a nice subject
  let subject = '';
  if (fileCategory === 'أحكام') {
    subject = `جلسة النطق بالحكم / استلام منطوق الحكم: ${fileName}`;
  } else if (fileCategory === 'مذكرات') {
    subject = `جلسة تقديم مذكرة الدفاع: ${fileName}`;
  } else if (fileCategory === 'صحف الدعاوى') {
    subject = `جلسة تقديم صحيفة الدعوى / إعلان العريضة: ${fileName}`;
  } else {
    subject = `جلسة متابعة مستندات: ${fileName}`;
  }

  return {
    isSuggested,
    session: {
      caseId: currentCase.id,
      caseNumber: currentCase.caseNumberFirstInstance,
      caseYear: currentCase.caseYearFirstInstance,
      clientName: currentCase.clientName,
      opponentName: currentCase.opponent?.name || (currentCase.opponentsList && currentCase.opponentsList[0]?.name) || 'غير محدد',
      court: currentCase.court,
      circuit: currentCase.circuit,
      type: currentCase.type,
      date: detectedDate,
      time: '09:00',
      subject: subject,
      status: 'pending',
      assignedLawyerId: currentCase.assignedLawyerId,
      notes: `تمت جدولة هذه الجلسة تلقائياً ومزامنتها بناءً على إرفاق ملف: ${fileName} المصنف كـ (${fileCategory})`
    }
  };
}

export interface UpcomingHearingInfo {
  session?: HearingSession;
  date?: string;
  time?: string;
  hasUpcoming: boolean;
  isExpert?: boolean;
  isDetention?: boolean;
}

/**
 * Resolves the closest actual upcoming hearing session for a given case from the sessions agenda.
 * Agenda is the primary single source of truth for upcoming sessions.
 * 
 * Criteria:
 * 1. Matches sessions associated with the case by caseId (or caseNumber/caseYear fallback).
 * 2. Filters for active/pending sessions scheduled for today or in the future (date >= today).
 *    - A session is upcoming if its date >= today and status !== 'completed'.
 *    - If a session is completed but has nextHearingDate >= today that is not yet a separate session, that next date is also considered.
 * 3. Sorts all upcoming candidate sessions chronologically (ascending by date, then time).
 * 4. Returns the earliest upcoming session. If none found, returns hasUpcoming = false.
 */
export function getClosestUpcomingSession(
  c: Case,
  sessions: HearingSession[] = []
): UpcomingHearingInfo {
  if (!c) {
    return { hasUpcoming: false };
  }

  // Calculate today's date in local YYYY-MM-DD
  const now = new Date();
  const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;

  // 1. Filter sessions for this case
  const caseSessions = (sessions || []).filter(s => {
    if (!s) return false;
    if (s.caseId && c.id && s.caseId === c.id) return true;
    if (s.caseNumber && c.caseNumberFirstInstance && s.caseNumber.trim() === c.caseNumberFirstInstance.trim()) {
      if (!s.caseYear || !c.caseYearFirstInstance || s.caseYear.trim() === c.caseYearFirstInstance.trim()) {
        return true;
      }
    }
    return false;
  });

  // Helper to determine if a session is a genuine detention renewal session
  const isActualDetentionSession = (s: HearingSession): boolean => {
    if (!s) return false;
    // الشرط الأول: أن تكون مرحلة التحقيق مفعّلة بالقضية وغير محالة للمحكمة
    if (!c.isInvestigationActive || isCaseReferredToCourt(c)) return false;
    if (s.isDetentionRenewal === false) return false;
    if (s.isDetentionRenewal === true) return true;
    if (s.detentionRenewalId || s.detentionRenewalNumber || s.detentionAuthority || s.detentionDurationDays) return true;
    if (s.id && (s.id.includes('detention') || s.id.includes('session-detention'))) return true;
    if (s.subject && (s.subject.includes('تجديد') || s.subject.includes('حبس') || s.subject.includes('احتياطي'))) return true;
    if (s.court && (s.court.includes('تجديد') || s.court.includes('مشورة'))) return true;
    if (c.detentionRenewals && c.detentionRenewals.length > 0) {
      const match = c.detentionRenewals.some(r =>
        (r.id && (r.id === s.detentionRenewalId || s.id?.includes(r.id))) ||
        ((r.date || r.renewalDate) === s.date) ||
        (r.nextRenewalDate === s.date)
      );
      if (match) return true;
    }
    return false;
  };

  // 2. Identify candidate upcoming sessions
  const candidateList: { session: HearingSession; date: string; time: string; isDetention: boolean; isExpert: boolean; isPast?: boolean }[] = [];
  const isReferred = isCaseReferredToCourt(c);

  for (const s of caseSessions) {
    const normDate = normalizeHearingDate(s.date);
    if (!normDate) continue;

    const isCompleted = s.status === 'completed' || (!!s.decision && s.decision.trim() !== '');

    const isExpert = !!(
      s.isExpertSession ||
      (s.court && (s.court.includes('خبراء') || s.court.includes('خبير'))) ||
      (s.subject && (s.subject.includes('خبراء') || s.subject.includes('خبير') || s.subject.includes('خبرة'))) ||
      c.isReferredToExperts ||
      c.expertReferral?.isReferred
    );

    const isDet = !isExpert && isActualDetentionSession(s);

    // إذا كانت القضية محالة للمحكمة: استبعد تماماً أي جلسة تجديد حبس من أن تكون جلسة قادمة
    if (isReferred && (isDet || s.isDetentionRenewal || (s.id && s.id.includes('detention')))) {
      continue;
    }

    // إذا اختار المستخدم «لا توجد جلسة محددة»، تُستبعد أي جلسة محاكمة عادية غير مبتوت فيها
    if (c.noUpcomingHearing && !isExpert && !isDet) {
      continue;
    }
    
    // 2. Identify candidate sessions (both future/today upcoming, and past sessions awaiting decision)
    if (!isCompleted) {
      if (normDate >= todayStr) {
        candidateList.push({
          session: s,
          date: normDate,
          time: s.time || '09:00',
          isDetention: isDet,
          isExpert,
          isPast: false
        });
      } else {
        candidateList.push({
          session: s,
          date: normDate,
          time: s.time || '09:00',
          isDetention: isDet,
          isExpert,
          isPast: true
        });
      }
    }

    // If the session has a postponed/nextHearingDate scheduled:
    if (s.nextHearingDate) {
      const normNextDate = normalizeHearingDate(s.nextHearingDate);
      if (normNextDate) {
        // Check if there is already a separate session in caseSessions with this date
        const hasSeparateSession = caseSessions.some(other => normalizeHearingDate(other.date) === normNextDate);
        if (!hasSeparateSession) {
          candidateList.push({
            session: s,
            date: normNextDate,
            time: s.time || '09:00',
            isDetention: isDet,
            isExpert,
            isPast: normNextDate < todayStr
          });
        }
      }
    }
  }

  // 3. Prioritize upcoming/today candidates first, then most recent past pending candidates
  const upcomingCandidates = candidateList.filter(c => !c.isPast);
  const pastPendingCandidates = candidateList.filter(c => c.isPast);

  if (upcomingCandidates.length > 0) {
    // Sort ascending: closest future/today session first
    upcomingCandidates.sort((a, b) => {
      const cmp = a.date.localeCompare(b.date);
      if (cmp !== 0) return cmp;
      return (a.time || '09:00').localeCompare(b.time || '09:00');
    });

    let chosen = upcomingCandidates[0];
    if (c.isInvestigationActive && !isCaseReferredToCourt(c)) {
      const upcomingDetention = upcomingCandidates.find(item => item.isDetention);
      if (upcomingDetention) {
        chosen = upcomingDetention;
      }
    }

    return {
      hasUpcoming: true,
      session: chosen.session,
      date: chosen.date,
      time: chosen.time,
      isExpert: chosen.isExpert,
      isDetention: chosen.isDetention
    };
  }

  if (pastPendingCandidates.length > 0) {
    // Sort descending: most recent past pending session first
    pastPendingCandidates.sort((a, b) => {
      const cmp = b.date.localeCompare(a.date);
      if (cmp !== 0) return cmp;
      return (b.time || '09:00').localeCompare(a.time || '09:00');
    });

    let chosen = pastPendingCandidates[0];
    if (c.isInvestigationActive && !isCaseReferredToCourt(c)) {
      const pendingDetention = pastPendingCandidates.find(item => item.isDetention);
      if (pendingDetention) {
        chosen = pendingDetention;
      }
    }

    return {
      hasUpcoming: true,
      session: chosen.session,
      date: chosen.date,
      time: chosen.time,
      isExpert: chosen.isExpert,
      isDetention: chosen.isDetention
    };
  }

  // If no session exists in the agenda, check if case has specified nextHearingDate:
  if (c.noUpcomingHearing) {
    return { hasUpcoming: false };
  }

  // If case has nextHearingDate specified (whether future, today, or in the past awaiting decision), resolve it directly:
  if (c.nextHearingDate) {
    const normCaseDate = normalizeHearingDate(c.nextHearingDate);
    if (normCaseDate) {
      const isExpert = !!(c.isReferredToExperts || c.expertReferral?.isReferred);
      const isDet = !isExpert && !isReferred && !!c.isInvestigationActive;
      return {
        hasUpcoming: true,
        date: normCaseDate,
        time: c.nextHearingTime || '09:00',
        isExpert,
        isDetention: isDet
      };
    }
  }

  return {
    hasUpcoming: false,
    isExpert: !!(c.isReferredToExperts || c.expertReferral?.isReferred),
    isDetention: false
  };
}

/**
 * Detects if a session is a detention renewal session.
 */
export function isDetentionSession(s: Partial<HearingSession>, parentCase?: Case | null): boolean {
  if (!s) return false;
  if (s.isDetentionRenewal === true) return true;
  if (s.isDetentionRenewal === false) return false;
  if (s.detentionRenewalId || s.detentionRenewalNumber || s.detentionAuthority || s.detentionDurationDays) return true;
  if (s.id && (s.id.startsWith('session-detention') || s.id.includes('detention'))) return true;
  const subj = (s.subject || '').trim();
  if (subj.includes('تجديد') || subj.includes('حبس') || subj.includes('احتياطي')) return true;
  const courtStr = (s.court || '').trim();
  if (courtStr.includes('تجديد') || courtStr.includes('مشورة')) return true;
  if (parentCase && parentCase.detentionRenewals && parentCase.detentionRenewals.length > 0) {
    return parentCase.detentionRenewals.some(r =>
      (r.id && (r.id === s.detentionRenewalId || s.id?.includes(r.id))) ||
      ((r.date || r.renewalDate) === s.date) ||
      (r.nextRenewalDate === s.date)
    );
  }
  return false;
}

/**
 * Cancels and deletes all upcoming detention renewal sessions for a given case in Firestore and local state,
 * while strictly preserving:
 * 1. All past detention sessions (date < today).
 * 2. All sessions that have a recorded decision or are completed (سجل تاريخي للعرض).
 * 3. All non-detention sessions (court hearings, expert sessions).
 * 4. The currently being recorded session (if currentSessionIdToKeep is specified).
 */
export async function cancelUpcomingDetentionSessionsForCase(
  targetCase: Case,
  allSessions: HearingSession[],
  currentSessionIdToKeep?: string,
  deleteDocFn?: (collectionName: string, id: string) => Promise<void>
): Promise<{ remainingSessions: HearingSession[]; deletedCount: number }> {
  const now = new Date();
  const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
  
  const toDelete: HearingSession[] = [];
  const toKeep: HearingSession[] = [];

  for (const s of allSessions) {
    // If not for this case, always keep
    const isThisCase = (s.caseId && targetCase.id && s.caseId === targetCase.id) ||
      (s.caseNumber && targetCase.caseNumberFirstInstance && s.caseNumber.trim() === targetCase.caseNumberFirstInstance.trim());
    if (!isThisCase) {
      toKeep.push(s);
      continue;
    }

    // Never delete the session currently being updated
    if (currentSessionIdToKeep && s.id === currentSessionIdToKeep) {
      toKeep.push(s);
      continue;
    }

    // Never delete expert sessions or court sessions
    if (s.isExpertSession || s.isDetentionRenewal === false) {
      toKeep.push(s);
      continue;
    }

    const isDet = isDetentionSession(s, targetCase);
    if (!isDet) {
      toKeep.push(s);
      continue;
    }

    // If it's a detention session:
    const hasDecision = !!s.decision && s.decision.trim() !== '';
    const isCompleted = s.status === 'completed';
    const normDate = normalizeHearingDate(s.date);
    const isPast = normDate < todayStr;

    // RULE: Preserve all past detention sessions and all sessions with decisions as historical records!
    if (isPast || hasDecision || isCompleted) {
      toKeep.push(s);
    } else {
      // It is an upcoming / pending detention renewal session with no decision -> DELETE IT!
      toDelete.push(s);
    }
  }

  // Delete from Firestore
  if (deleteDocFn && toDelete.length > 0) {
    for (const d of toDelete) {
      try {
        await deleteDocFn('sessions', d.id);
      } catch (err) {
        console.warn(`Failed to delete upcoming detention session ${d.id}:`, err);
      }
    }
  }

  return {
    remainingSessions: toKeep,
    deletedCount: toDelete.length
  };
}
