/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Case, HearingSession } from '../types';

/**
 * Converts Arabic-Indic numerals (e.g., ٠١٢٣٤٥٦٧٨٩) to standard Western Arabic numerals (0-9).
 */
export function convertArabicIndicDigits(str: string): string {
  const map: { [key: string]: string } = {
    '٠': '0', '١': '1', '٢': '2', '٣': '3', '٤': '4',
    '٥': '5', '٦': '6', '٧': '7', '٨': '8', '٩': '9'
  };
  return str.replace(/[٠-٩]/g, (d) => map[d] || d);
}

/**
 * Normalizes any date string (with Arabic-Indic numerals, slashes, or dashes) to standard Western YYYY-MM-DD.
 */
export function normalizeHearingDate(d?: string): string {
  if (!d) return '';
  const clean = convertArabicIndicDigits(d.trim()).replace(/\//g, '-');
  const parts = clean.split('-');
  if (parts.length === 3) {
    const y = parts[0].padStart(4, '20');
    const m = parts[1].padStart(2, '0');
    const day = parts[2].padStart(2, '0');
    return `${y}-${m}-${day}`;
  }
  return clean;
}

/**
 * Scans a string for date patterns and returns them in YYYY-MM-DD format if found.
 * Supports:
 * - YYYY-MM-DD or YYYY/MM/DD
 * - DD-MM-YYYY or DD/MM/YYYY
 * - DD-MM or DD/MM (uses current year)
 */
export function extractHearingDate(text: string): string | null {
  if (!text) return null;
  
  const cleanText = convertArabicIndicDigits(text);
  
  // 1. Match YYYY-MM-DD or YYYY/MM/DD
  const ymdRegex = /(?:^|[^0-9])(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})(?:$|[^0-9])/;
  const ymdMatch = cleanText.match(ymdRegex);
  if (ymdMatch) {
    const year = parseInt(ymdMatch[1], 10);
    const month = parseInt(ymdMatch[2], 10);
    const day = parseInt(ymdMatch[3], 10);
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    }
  }

  // 2. Match DD-MM-YYYY or DD/MM/YYYY
  const dmyRegex = /(?:^|[^0-9])(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})(?:$|[^0-9])/;
  const dmyMatch = cleanText.match(dmyRegex);
  if (dmyMatch) {
    const day = parseInt(dmyMatch[1], 10);
    const month = parseInt(dmyMatch[2], 10);
    const year = parseInt(dmyMatch[3], 10);
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    }
  }

  // 3. Match DD-MM or DD/MM (without year, fallback to current year)
  const dmRegex = /(?:^|[^0-9])(\d{1,2})[-/.](\d{1,2})(?:$|[^0-9])/;
  const dmMatch = cleanText.match(dmRegex);
  if (dmMatch) {
    const day = parseInt(dmMatch[1], 10);
    const month = parseInt(dmMatch[2], 10);
    const year = new Date().getFullYear();
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      // Ensure we don't accidentally match something like 15-05 in "Case 15-05" unless it's likely a date
      // We can check if the surrounding context contains calendar words
      const dateIndicatorKeywords = ['جلسة', 'تاريخ', 'يوم', 'جلسه', 'شهر', 'عام'];
      const hasIndicator = dateIndicatorKeywords.some(kw => (text || '').includes(kw));
      if (hasIndicator) {
        return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
      }
    }
  }

  return null;
}

/**
 * Checks if a file name or category suggests it relates to a court hearing session.
 */
export function isAutoGeneratedSessionId(id: string): boolean {
  return (
    id.startsWith('session-expert-') ||
    id.startsWith('session-detention-') ||
    id.startsWith('session-proc-') ||
    id.startsWith('session-file-') ||
    id.startsWith('session-sync-expert-') ||
    id.startsWith('session-detention-next-') ||
    id.startsWith('session-detention-prev-')
  );
}

/**
 * Categorizes a session into 'expert', 'detention', or court/regular case type.
 */
export function getSessionCategory(s: Partial<HearingSession>, parentCase?: Case | null): string {
  if (!s) return parentCase?.type || 'court';

  const isExp = !!(
    s.isExpertSession ||
    (s.id && s.id.includes('expert')) ||
    (s.court && (s.court.includes('خبراء') || s.court.includes('خبير'))) ||
    (s.subject && (s.subject.includes('خبراء') || s.subject.includes('خبير') || s.subject.includes('خبرة'))) ||
    parentCase?.isReferredToExperts ||
    parentCase?.expertReferral?.isReferred
  );
  if (isExp) return 'expert';

  const isDet = !!(
    s.isDetentionRenewal ||
    (s.id && s.id.includes('detention')) ||
    (s.court && (s.court.includes('تجديد') || s.court.includes('مشورة'))) ||
    (s.subject && (s.subject.includes('تجديد') || s.subject.includes('حبس') || s.subject.includes('احتياطي'))) ||
    parentCase?.isInvestigationActive
  );
  if (isDet) return 'detention';

  return (s.type || parentCase?.type || 'court').trim();
}

/**
 * Checks if two sessions represent the exact same session based on (case + date + session category).
 */
export function isSameSession(s1: Partial<HearingSession>, s2: Partial<HearingSession>, cases?: Case[]): boolean {
  if (!s1 || !s2) return false;
  if (s1.id && s2.id && s1.id === s2.id) return true;

  const date1 = normalizeHearingDate(s1.date);
  const date2 = normalizeHearingDate(s2.date);
  if (!date1 || !date2 || date1 !== date2) return false;

  const c1 = cases?.find(c => c.id === s1.caseId);
  const c2 = cases?.find(c => c.id === s2.caseId);

  const isSameCase = 
    (s1.caseId && s2.caseId && s1.caseId === s2.caseId) ||
    (s1.caseNumber && s2.caseNumber && s1.caseNumber === s2.caseNumber && (!s1.caseYear || !s2.caseYear || s1.caseYear === s2.caseYear));

  if (!isSameCase) return false;

  const cat1 = getSessionCategory(s1, c1);
  const cat2 = getSessionCategory(s2, c2);

  return cat1 === cat2;
}

/**
 * Finds an existing session matching an incoming session by (caseId + date + session category).
 */
export function findMatchingSession(
  existingSessions: HearingSession[], 
  target: Partial<HearingSession>, 
  parentCase?: Case | null,
  cases?: Case[]
): HearingSession | undefined {
  if (!target) return undefined;
  
  // 1. Direct ID match
  if (target.id) {
    const direct = existingSessions.find(s => s.id === target.id);
    if (direct) return direct;
  }

  const targetDate = normalizeHearingDate(target.date);
  if (!targetDate) return undefined;

  const targetCaseId = target.caseId || parentCase?.id;
  const targetCaseNum = target.caseNumber || parentCase?.caseNumberFirstInstance;
  const targetCaseYear = target.caseYear || parentCase?.caseYearFirstInstance;
  const targetCategory = getSessionCategory(target, parentCase);

  return existingSessions.find(s => {
    // Check date
    if (normalizeHearingDate(s.date) !== targetDate) return false;

    // Check case
    const isSameCase = (targetCaseId && s.caseId === targetCaseId) ||
      (targetCaseNum && s.caseNumber === targetCaseNum && (!targetCaseYear || !s.caseYear || targetCaseYear === s.caseYear));
    if (!isSameCase) return false;

    // Check category/type
    const sCase = parentCase || cases?.find(c => c.id === s.caseId);
    const sCategory = getSessionCategory(s, sCase);
    return sCategory === targetCategory;
  });
}

/**
 * Merges incoming session updates into an existing session while preserving original session ID,
 * history, decisions, notes, and requirements.
 */
export function mergeSessionData(existing: HearingSession, incoming: Partial<HearingSession>): HearingSession {
  const normIncomingDate = normalizeHearingDate(incoming.date);
  const normIncomingNextDate = normalizeHearingDate(incoming.nextHearingDate);
  const normExistingDate = normalizeHearingDate(existing.date);
  const normExistingNextDate = normalizeHearingDate(existing.nextHearingDate);

  const hasNewDecision = incoming.decision !== undefined && incoming.decision !== null && incoming.decision.trim() !== '';

  return {
    ...existing,
    ...incoming,
    id: existing.id, // ALWAYS preserve the original ID!
    caseId: existing.caseId || incoming.caseId || '',
    caseNumber: existing.caseNumber || incoming.caseNumber || '',
    caseYear: existing.caseYear || incoming.caseYear || '',
    clientName: incoming.clientName || existing.clientName || '',
    opponentName: incoming.opponentName || existing.opponentName || 'غير محدد',
    date: normIncomingDate || normExistingDate,
    time: incoming.time || existing.time || '09:00',
    court: incoming.court || existing.court || '',
    circuit: incoming.circuit || existing.circuit || '',
    type: incoming.type || existing.type || 'مدني',
    subject: incoming.subject || existing.subject || 'جلسة متداولة ومتابعة',
    decision: hasNewDecision ? incoming.decision!.trim() : existing.decision,
    nextHearingDate: normIncomingNextDate || normExistingNextDate || undefined,
    status: hasNewDecision 
      ? (incoming.status === 'postponed' ? 'postponed' : 'completed')
      : (incoming.status || existing.status || 'pending'),
    whatHappened: incoming.whatHappened || existing.whatHappened,
    requirements: incoming.requirements || existing.requirements,
    rollPhotoUrl: incoming.rollPhotoUrl || existing.rollPhotoUrl,
    notes: incoming.notes || existing.notes,
    assignedLawyerId: incoming.assignedLawyerId || existing.assignedLawyerId,
    assignedLawyerName: incoming.assignedLawyerName || existing.assignedLawyerName,
    isDetentionRenewal: incoming.isDetentionRenewal ?? existing.isDetentionRenewal,
    detentionStartDate: incoming.detentionStartDate || existing.detentionStartDate,
    detentionDurationDays: incoming.detentionDurationDays || existing.detentionDurationDays,
    detentionDuration: incoming.detentionDuration || existing.detentionDuration,
    detentionRenewalNumber: incoming.detentionRenewalNumber || existing.detentionRenewalNumber,
    detentionDecisionNumber: incoming.detentionDecisionNumber || existing.detentionDecisionNumber,
    detentionAuthority: incoming.detentionAuthority || existing.detentionAuthority,
    detentionNextAuthority: incoming.detentionNextAuthority || existing.detentionNextAuthority,
    detentionRenewalId: incoming.detentionRenewalId || existing.detentionRenewalId,
    isExpertSession: incoming.isExpertSession ?? existing.isExpertSession,
    expertSessionId: incoming.expertSessionId || existing.expertSessionId
  };
}

/**
 * Deduplicates an array of sessions based on (caseId + normalizedDate + sessionCategory),
 * merging duplicates into single comprehensive records with all decisions and notes preserved.
 */
export function deduplicateSessions(sessions: HearingSession[], cases?: Case[]): HearingSession[] {
  if (!sessions || sessions.length === 0) return [];

  const map = new Map<string, HearingSession>();

  for (const s of sessions) {
    const normDate = normalizeHearingDate(s.date);
    if (!normDate) continue;

    const parentCase = cases?.find(c => c.id === s.caseId || (c.caseNumberFirstInstance === s.caseNumber && (!s.caseYear || c.caseYearFirstInstance === s.caseYear)));
    const cat = getSessionCategory(s, parentCase);
    const caseKey = s.caseId || `${s.caseNumber}_${s.caseYear || ''}`;
    const dedupeKey = `${caseKey}_${normDate}_${cat}`;

    const existing = map.get(dedupeKey);
    if (!existing) {
      map.set(dedupeKey, { ...s, date: normDate });
    } else {
      // Prioritize the record that has a decision, completed status, or an established ID
      const merged = mergeSessionData(existing, s);
      map.set(dedupeKey, merged);
    }
  }

  return Array.from(map.values());
}

/**
 * Extracts all expected automated hearing sessions from a given case.
 */
export function generateExpectedAutoSessionsForCase(c: Case, users: any[] = []): HearingSession[] {
  const result: HearingSession[] = [];
  if (!c || c.isArchived) return result;

  const assignedLawyerName = users.find(u => u.id === c.assignedLawyerId)?.fullName || undefined;

  // 1. Files scan
  if (c.files) {
    c.files.forEach(file => {
      const fileDate = extractHearingDate(file.name);
      if (!fileDate) return;
      const sessionId = `session-file-${c.id}-${file.id}`;
      result.push({
        id: sessionId,
        caseId: c.id,
        caseNumber: c.caseNumberFirstInstance,
        caseYear: c.caseYearFirstInstance,
        clientName: c.clientName,
        opponentName: c.opponent ? c.opponent.name : 'غير محدد',
        court: c.court || 'غير محدد',
        circuit: c.circuit || 'غير محدد',
        type: c.type,
        date: fileDate,
        time: '09:00',
        subject: `جلسة مستخرجة ومزامنة تلقائياً من مستند: ${file.name}`,
        status: 'pending',
        assignedLawyerId: c.assignedLawyerId || undefined,
        assignedLawyerName,
        notes: `تم رصد الجلسة وإضافتها تلقائياً بناءً على الملف: ${file.name}`
      });
    });
  }

  // 2. Expert sessions scan
  if ((c.isReferredToExperts || c.expertReferral?.isReferred) && c.expertReferral) {
    // 2.1 First session date if specified AND not already included in sessions array
    const hasFirstInSessions = c.expertReferral.firstSessionDate && c.expertReferral.sessions?.some(s => s.date === c.expertReferral?.firstSessionDate);
    if (c.expertReferral.firstSessionDate && !hasFirstInSessions) {
      const firstSessId = `session-expert-first-${c.id}`;
      result.push({
        id: firstSessId,
        caseId: c.id,
        caseNumber: c.caseNumberFirstInstance,
        caseYear: c.caseYearFirstInstance,
        clientName: c.clientName,
        opponentName: c.opponent?.name || 'غير محدد',
        court: c.expertReferral.expertOffice || c.court || 'مكتب خبراء وزارة العدل',
        circuit: c.expertReferral.courtOrCircuit || 'جلسة خبراء أولى',
        type: c.type,
        date: c.expertReferral.firstSessionDate,
        time: '10:00',
        subject: `جلسة خبراء أولى - ${c.expertReferral.expertOffice || 'مكتب الخبراء'} (الخبير: ${c.expertReferral.expertName || 'غير محدد'})`,
        status: 'pending',
        decision: undefined,
        assignedLawyerId: c.assignedLawyerId || undefined,
        assignedLawyerName,
        notes: `جلسة إحالة للخبراء الأولى محددة بالقضية. ${c.expertReferral.referralReason || ''}`,
        isExpertSession: true,
        expertSessionId: 'first-session'
      });
    }

    // 2.2 Sessions array
    if (c.expertReferral.sessions && c.expertReferral.sessions.length > 0) {
      c.expertReferral.sessions.forEach((expSess, idx) => {
        if (expSess.date) {
          const expKey = expSess.id || `exp-${idx}`;
          const sessionId = `session-expert-${c.id}-${expKey}`;
          const hasRealDecision = !!expSess.decisionOrAction && expSess.decisionOrAction.trim() !== '';
          const effectiveStatus = expSess.status === 'pending'
            ? 'pending'
            : expSess.status === 'postponed'
            ? 'postponed'
            : (hasRealDecision || expSess.status === 'completed')
            ? 'completed'
            : 'pending';

          result.push({
            id: sessionId,
            caseId: c.id,
            caseNumber: c.caseNumberFirstInstance,
            caseYear: c.caseYearFirstInstance,
            clientName: c.clientName,
            opponentName: c.opponent?.name || 'غير محدد',
            court: c.expertReferral?.expertOffice || c.court || 'مكتب خبراء وزارة العدل',
            circuit: expSess.location || 'جلسة خبراء',
            type: c.type,
            date: expSess.date,
            time: expSess.time || '10:00',
            subject: `جلسة خبرة (${expSess.sessionType || 'حضور الخبير'}) - ${expSess.location || c.expertReferral?.expertOffice || 'مكتب الخبراء'}`,
            status: effectiveStatus,
            decision: hasRealDecision ? expSess.decisionOrAction : undefined,
            assignedLawyerId: c.assignedLawyerId || undefined,
            assignedLawyerName,
            notes: expSess.notes || 'جلسة خبراء مسجلة في ملف القضية.',
            isExpertSession: true,
            expertSessionId: expKey
          });
        }

        // Next session date if set and distinct from current session date and not already an explicit session item
        if (expSess.nextSessionDate && expSess.nextSessionDate !== expSess.date) {
          const hasNextInArray = c.expertReferral?.sessions?.some(s => s.date === expSess.nextSessionDate);
          if (!hasNextInArray) {
            const nextKey = `session-expert-next-${c.id}-${expSess.id || idx}`;
            result.push({
              id: nextKey,
              caseId: c.id,
              caseNumber: c.caseNumberFirstInstance,
              caseYear: c.caseYearFirstInstance,
              clientName: c.clientName,
              opponentName: c.opponent?.name || 'غير محدد',
              court: c.expertReferral?.expertOffice || 'مكتب خبراء وزارة العدل',
              circuit: expSess.location || c.expertReferral?.courtOrCircuit || 'جلسة مباشرة الخبير',
              type: c.type,
              date: expSess.nextSessionDate,
              time: '10:00',
              subject: `جلسة خبرة ومباشرة قادمة (${expSess.sessionType || 'متابعة'}) - ${expSess.location || c.expertReferral?.expertOffice || 'مكتب الخبراء'}`,
              status: 'pending',
              decision: undefined,
              assignedLawyerId: c.assignedLawyerId || undefined,
              assignedLawyerName,
              notes: `جلسة خبراء مؤجلة بناءً على قرار الجلسة السابقة: ${expSess.decisionOrAction || ''}`,
              isExpertSession: true,
              expertSessionId: `next-${expSess.id || idx}`
            });
          }
        }
      });
    }
  }

  // 3. Detention Renewals scan (سجل تجديدات الحبس الاحتياطي - مشروط حصرياً بتفعيل مرحلة التحقيق)
  if (c.isInvestigationActive && c.detentionRenewals && c.detentionRenewals.length > 0) {
    c.detentionRenewals.forEach((ren, idx) => {
      const renKey = ren.id || `ren-${idx}`;
      const renDate = ren.date || ren.renewalDate;

      // Check if both dates exist and are different, and that nextRenewalDate isn't already covered by another explicit renewal record
      const isNextDateCovered = c.detentionRenewals!.some(r => (r.id !== renKey) && ((r.date || r.renewalDate) === ren.nextRenewalDate));
      const hasDistinctNextDate = !!(ren.nextRenewalDate && renDate && ren.nextRenewalDate !== renDate && !isNextDateCovered);
      const effectiveDate = renDate || ren.nextRenewalDate;

      // A. Upcoming detention renewal session (when distinct next date exists)
      if (hasDistinctNextDate && ren.nextRenewalDate) {
        const nextSessionId = `session-detention-next-${c.id}-${renKey}`;
        result.push({
          id: nextSessionId,
          caseId: c.id,
          caseNumber: c.investigationNumber ? `${c.investigationNumber}/${c.investigationYear || c.caseYearFirstInstance}` : c.caseNumberFirstInstance,
          caseYear: c.investigationYear || c.caseYearFirstInstance,
          clientName: c.clientName,
          opponentName: c.investigationAuthority || (c.opponent?.name || 'النيابة العامة'),
          court: ren.court || ren.nextAuthority || ren.authority || c.investigationAuthority || c.court || 'النيابة العامة / غرفة المشورة',
          circuit: ren.circuit || c.circuit || 'دائرة تجديد الحبس',
          type: c.type || 'جنح',
          date: ren.nextRenewalDate,
          time: '09:00',
          subject: `جلسة تجديد حبس احتياطي (${ren.nextAuthority || ren.authority || 'جهة التجديد'})`,
          status: 'pending',
          assignedLawyerId: c.assignedLawyerId || undefined,
          assignedLawyerName,
          notes: `جلسة تجديد حبس احتياطي قادمة للمتهم/الموكل: ${c.clientName}. ${ren.notes || ''}`,
          isDetentionRenewal: true,
          detentionStartDate: ren.detentionStartDate || c.detentionStartDate,
          detentionAuthority: ren.nextAuthority || ren.authority,
          detentionNextAuthority: ren.nextAuthority,
          detentionDurationDays: ren.durationDays,
          detentionDuration: ren.duration || (ren.durationDays ? `${ren.durationDays} يوم` : undefined),
          detentionRenewalNumber: ren.renewalNumber ? (Number(ren.renewalNumber) + 1) : (idx + 2),
          detentionRenewalId: renKey
        });
      }

      // B. Primary / Recorded renewal session date
      if (effectiveDate) {
        const renSessionId = `session-detention-prev-${c.id}-${renKey}`;
        const hasDecision = !!ren.decision && ren.decision.trim() !== '';
        result.push({
          id: renSessionId,
          caseId: c.id,
          caseNumber: c.investigationNumber ? `${c.investigationNumber}/${c.investigationYear || c.caseYearFirstInstance}` : c.caseNumberFirstInstance,
          caseYear: c.investigationYear || c.caseYearFirstInstance,
          clientName: c.clientName,
          opponentName: c.investigationAuthority || (c.opponent?.name || 'النيابة العامة'),
          court: ren.court || ren.authority || c.investigationAuthority || c.court || 'النيابة العامة',
          circuit: ren.circuit || c.circuit || 'دائرة تجديد الحبس',
          type: c.type || 'جنح',
          date: effectiveDate,
          time: '09:00',
          subject: `جلسة تجديد حبس احتياطي (${ren.authority || 'النيابة العامة'})`,
          status: hasDecision ? 'completed' : 'pending',
          decision: hasDecision ? ren.decision : undefined,
          nextHearingDate: (ren.nextRenewalDate && ren.nextRenewalDate !== effectiveDate) ? ren.nextRenewalDate : undefined,
          assignedLawyerId: c.assignedLawyerId || undefined,
          assignedLawyerName,
          notes: `جلسة تجديد حبس احتياطي مسجلة في ملف القضية. ${ren.notes || ''}`,
          isDetentionRenewal: true,
          detentionStartDate: ren.detentionStartDate || c.detentionStartDate,
          detentionAuthority: ren.authority,
          detentionNextAuthority: ren.nextAuthority,
          detentionDurationDays: ren.durationDays,
          detentionDuration: ren.duration || (ren.durationDays ? `${ren.durationDays} يوم` : undefined),
          detentionRenewalNumber: ren.renewalNumber || (idx + 1),
          detentionDecisionNumber: ren.decisionNumber,
          detentionRenewalId: renKey
        });
      }
    });
  }

  // 4. Investigation Procedures scan (سجل إجراءات التحقيق بالنيابة - يتم إنشاؤها فقط عند تفعيل مرحلة التحقيق)
  if (c.isInvestigationActive && c.investigationProcedures && c.investigationProcedures.length > 0) {
    c.investigationProcedures.forEach((proc, idx) => {
      if (proc.sessionDate) {
        const isDetention = (proc.actionType || '').includes('تجديد') || (proc.actionType || '').includes('حبس') || (proc.actionType || '').includes('استئناف أمر الحبس') || (proc.actionType || '').includes('تحقيق');
        const procKey = proc.id || `proc-${idx}`;
        const procSessionId = `session-proc-${c.id}-${procKey}`;
        result.push({
          id: procSessionId,
          caseId: c.id,
          caseNumber: c.investigationNumber ? `${c.investigationNumber}/${c.investigationYear || c.caseYearFirstInstance}` : c.caseNumberFirstInstance,
          caseYear: c.investigationYear || c.caseYearFirstInstance,
          clientName: c.clientName,
          opponentName: proc.authority || c.investigationAuthority || 'النيابة العامة',
          court: proc.authority || c.court || 'النيابة العامة',
          circuit: c.circuit || 'غرفة المشورة / التحقيق',
          type: c.type || 'جنائي',
          date: proc.sessionDate,
          time: '09:00',
          subject: `جلسة ${proc.actionType || 'تجديد حبس احتياطي'} - ${proc.authority || 'النيابة العامة'}`,
          status: proc.decision ? 'completed' : 'pending',
          decision: proc.decision,
          assignedLawyerId: c.assignedLawyerId || undefined,
          assignedLawyerName,
          notes: `إجراء تحقيق وتجديد حبس مسجل بملف التحقيقات. ${proc.notes || ''}`,
          isDetentionRenewal: isDetention,
          detentionAuthority: proc.authority,
          detentionDurationDays: proc.renewalDays || 15
        });
      }
    });
  }

  return deduplicateSessions(result, [c]);
}

/**
 * Extracts all expected automated hearing sessions from all active cases.
 */
export function generateExpectedAutoSessionsForAllCases(cases: Case[], users: any[] = []): Map<string, HearingSession> {
  const map = new Map<string, HearingSession>();
  if (!cases || cases.length === 0) return map;

  cases.forEach(c => {
    const sessions = generateExpectedAutoSessionsForCase(c, users);
    sessions.forEach(sess => {
      map.set(sess.id, sess);
    });
  });

  return map;
}

/**
 * Checks if a file name or category suggests it relates to a court hearing session.
 */
export function checkIfRelatesToHearing(fileName: string, fileCategory: string): boolean {
  const lowerFileName = (fileName || '').toLowerCase();
  
  // Keywords indicating hearing
  const hearingKeywords = [
    'جلسة', 'جلسه', 'حضور', 'رول', 'محضر', 'مرافعة', 
    'مرافعه', 'مذكرة', 'مذكره', 'دفاع', 'حكم', 'قرار', 'تأجيل', 'أجندة', 'اجندة'
  ];
  
  const hasKeyword = hearingKeywords.some(kw => lowerFileName.includes(kw));
  const isHearingCategory = fileCategory ? ['صحف الدعاوى', 'مذكرات', 'أحكام'].includes(fileCategory) : false;
  
  return hasKeyword || isHearingCategory;
}

/**
 * Generates a pre-filled suggestion for a hearing session based on the file metadata.
 */
export function suggestHearingSession(
  fileName: string, 
  fileCategory: string, 
  currentCase: Case
): {
  isSuggested: boolean;
  session: Omit<HearingSession, 'id'>;
} {
  const isSuggested = checkIfRelatesToHearing(fileName, fileCategory);
  const today = new Date();
  const localDateStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;
  const detectedDate = extractHearingDate(fileName) || currentCase.nextHearingDate || localDateStr;
  
  // Build a nice subject
  let subject = '';
  if (fileCategory === 'أحكام') {
    subject = `جلسة النطق بالحكم / استلام منطوق الحكم: ${fileName}`;
  } else if (fileCategory === 'مذكرات') {
    subject = `جلسة تقديم مذكرة الدفاع: ${fileName}`;
  } else if (fileCategory === 'صحف الدعاوى') {
    subject = `جلسة تقديم صحيفة الدعوى / إعلان العريضة: ${fileName}`;
  } else {
    subject = `جلسة متابعة مستندات: ${fileName}`;
  }

  return {
    isSuggested,
    session: {
      caseId: currentCase.id,
      caseNumber: currentCase.caseNumberFirstInstance,
      caseYear: currentCase.caseYearFirstInstance,
      clientName: currentCase.clientName,
      opponentName: currentCase.opponent.name,
      court: currentCase.court,
      circuit: currentCase.circuit,
      type: currentCase.type,
      date: detectedDate,
      time: '09:00',
      subject: subject,
      status: 'pending',
      assignedLawyerId: currentCase.assignedLawyerId,
      notes: `تمت جدولة هذه الجلسة تلقائياً ومزامنتها بناءً على إرفاق ملف: ${fileName} المصنف كـ (${fileCategory})`
    }
  };
}

export interface UpcomingHearingInfo {
  session?: HearingSession;
  date?: string;
  time?: string;
  hasUpcoming: boolean;
  isExpert?: boolean;
  isDetention?: boolean;
}

/**
 * Resolves the closest actual upcoming hearing session for a given case from the sessions agenda.
 * Agenda is the primary single source of truth for upcoming sessions.
 * 
 * Criteria:
 * 1. Matches sessions associated with the case by caseId (or caseNumber/caseYear fallback).
 * 2. Filters for active/pending sessions scheduled for today or in the future (date >= today).
 *    - A session is upcoming if its date >= today and status !== 'completed'.
 *    - If a session is completed but has nextHearingDate >= today that is not yet a separate session, that next date is also considered.
 * 3. Sorts all upcoming candidate sessions chronologically (ascending by date, then time).
 * 4. Returns the earliest upcoming session. If none found, returns hasUpcoming = false.
 */
export function getClosestUpcomingSession(
  c: Case,
  sessions: HearingSession[] = []
): UpcomingHearingInfo {
  if (!c) {
    return { hasUpcoming: false };
  }

  // Calculate today's date in local YYYY-MM-DD
  const now = new Date();
  const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;

  // 1. Filter sessions for this case
  const caseSessions = (sessions || []).filter(s => {
    if (!s) return false;
    if (s.caseId && c.id && s.caseId === c.id) return true;
    if (s.caseNumber && c.caseNumberFirstInstance && s.caseNumber.trim() === c.caseNumberFirstInstance.trim()) {
      if (!s.caseYear || !c.caseYearFirstInstance || s.caseYear.trim() === c.caseYearFirstInstance.trim()) {
        return true;
      }
    }
    return false;
  });

  // 2. Identify candidate upcoming sessions
  const candidateList: { session: HearingSession; date: string; time: string }[] = [];

  for (const s of caseSessions) {
    const normDate = normalizeHearingDate(s.date);
    if (!normDate) continue;

    const isCompleted = s.status === 'completed' || (!!s.decision && s.decision.trim() !== '');
    
    // If not completed and date is today or future:
    if (normDate >= todayStr && !isCompleted) {
      candidateList.push({
        session: s,
        date: normDate,
        time: s.time || '09:00'
      });
    }

    // If the session has a postponed/nextHearingDate scheduled for today or future:
    if (s.nextHearingDate) {
      const normNextDate = normalizeHearingDate(s.nextHearingDate);
      if (normNextDate && normNextDate >= todayStr) {
        // Check if there is already a separate session in caseSessions with this date
        const hasSeparateSession = caseSessions.some(other => normalizeHearingDate(other.date) === normNextDate);
        if (!hasSeparateSession) {
          candidateList.push({
            session: s,
            date: normNextDate,
            time: s.time || '09:00'
          });
        }
      }
    }
  }

  // 3. Sort ascending by date, then time
  candidateList.sort((a, b) => {
    const cmp = a.date.localeCompare(b.date);
    if (cmp !== 0) return cmp;
    return (a.time || '09:00').localeCompare(b.time || '09:00');
  });

  if (candidateList.length > 0) {
    const closest = candidateList[0];
    const s = closest.session;

    const isExpert = !!(
      s.isExpertSession ||
      (s.court && (s.court.includes('خبراء') || s.court.includes('خبير'))) ||
      (s.subject && (s.subject.includes('خبراء') || s.subject.includes('خبير') || s.subject.includes('خبرة'))) ||
      c.isReferredToExperts ||
      c.expertReferral?.isReferred
    );

    const isDetention = !isExpert && !!(
      s.isDetentionRenewal ||
      (s.court && (s.court.includes('تجديد') || s.court.includes('مشورة'))) ||
      (s.subject && (s.subject.includes('تجديد') || s.subject.includes('حبس') || s.subject.includes('احتياطي'))) ||
      c.isInvestigationActive
    );

    return {
      hasUpcoming: true,
      session: s,
      date: closest.date,
      time: closest.time,
      isExpert,
      isDetention
    };
  }

  // If no upcoming session exists in the agenda, check if case has sessions at all:
  // If caseSessions has records, then there genuinely are NO upcoming sessions (all past or deleted).
  // If caseSessions is empty (case newly created without sessions yet), check c.nextHearingDate:
  if (caseSessions.length === 0 && c.nextHearingDate) {
    const normCaseDate = normalizeHearingDate(c.nextHearingDate);
    if (normCaseDate >= todayStr) {
      const isExpert = !!(c.isReferredToExperts || c.expertReferral?.isReferred);
      const isDetention = !isExpert && !!c.isInvestigationActive;
      return {
        hasUpcoming: true,
        date: normCaseDate,
        time: c.nextHearingTime || '09:00',
        isExpert,
        isDetention
      };
    }
  }

  return {
    hasUpcoming: false,
    isExpert: !!(c.isReferredToExperts || c.expertReferral?.isReferred),
    isDetention: !!c.isInvestigationActive
  };
}
