/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Case, HearingSession } from '../types';

/**
 * Converts Arabic-Indic numerals (e.g., ٠١٢٣٤٥٦٧٨٩) to standard Western Arabic numerals (0-9).
 */
export function convertArabicIndicDigits(str: string): string {
  const map: { [key: string]: string } = {
    '٠': '0', '١': '1', '٢': '2', '٣': '3', '٤': '4',
    '٥': '5', '٦': '6', '٧': '7', '٨': '8', '٩': '9'
  };
  return str.replace(/[٠-٩]/g, (d) => map[d] || d);
}

/**
 * Scans a string for date patterns and returns them in YYYY-MM-DD format if found.
 * Supports:
 * - YYYY-MM-DD or YYYY/MM/DD
 * - DD-MM-YYYY or DD/MM/YYYY
 * - DD-MM or DD/MM (uses current year)
 */
export function extractHearingDate(text: string): string | null {
  if (!text) return null;
  
  const cleanText = convertArabicIndicDigits(text);
  
  // 1. Match YYYY-MM-DD or YYYY/MM/DD
  const ymdRegex = /(?:^|[^0-9])(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})(?:$|[^0-9])/;
  const ymdMatch = cleanText.match(ymdRegex);
  if (ymdMatch) {
    const year = parseInt(ymdMatch[1], 10);
    const month = parseInt(ymdMatch[2], 10);
    const day = parseInt(ymdMatch[3], 10);
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    }
  }

  // 2. Match DD-MM-YYYY or DD/MM/YYYY
  const dmyRegex = /(?:^|[^0-9])(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})(?:$|[^0-9])/;
  const dmyMatch = cleanText.match(dmyRegex);
  if (dmyMatch) {
    const day = parseInt(dmyMatch[1], 10);
    const month = parseInt(dmyMatch[2], 10);
    const year = parseInt(dmyMatch[3], 10);
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    }
  }

  // 3. Match DD-MM or DD/MM (without year, fallback to current year)
  const dmRegex = /(?:^|[^0-9])(\d{1,2})[-/.](\d{1,2})(?:$|[^0-9])/;
  const dmMatch = cleanText.match(dmRegex);
  if (dmMatch) {
    const day = parseInt(dmMatch[1], 10);
    const month = parseInt(dmMatch[2], 10);
    const year = new Date().getFullYear();
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      // Ensure we don't accidentally match something like 15-05 in "Case 15-05" unless it's likely a date
      // We can check if the surrounding context contains calendar words
      const dateIndicatorKeywords = ['جلسة', 'تاريخ', 'يوم', 'جلسه', 'شهر', 'عام'];
      const hasIndicator = dateIndicatorKeywords.some(kw => (text || '').includes(kw));
      if (hasIndicator) {
        return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
      }
    }
  }

  return null;
}

/**
 * Checks if a file name or category suggests it relates to a court hearing session.
 */
export function isAutoGeneratedSessionId(id: string): boolean {
  return (
    id.startsWith('session-expert-') ||
    id.startsWith('session-detention-') ||
    id.startsWith('session-proc-') ||
    id.startsWith('session-file-') ||
    id.startsWith('session-sync-expert-') ||
    id.startsWith('session-detention-next-') ||
    id.startsWith('session-detention-prev-')
  );
}

/**
 * Extracts all expected automated hearing sessions from a given case.
 */
export function generateExpectedAutoSessionsForCase(c: Case, users: any[] = []): HearingSession[] {
  const result: HearingSession[] = [];
  if (!c || c.isArchived) return result;

  const assignedLawyerName = users.find(u => u.id === c.assignedLawyerId)?.fullName || undefined;

  // 1. Files scan
  if (c.files) {
    c.files.forEach(file => {
      const fileDate = extractHearingDate(file.name);
      if (!fileDate) return;
      const sessionId = `session-file-${c.id}-${file.id}`;
      result.push({
        id: sessionId,
        caseId: c.id,
        caseNumber: c.caseNumberFirstInstance,
        caseYear: c.caseYearFirstInstance,
        clientName: c.clientName,
        opponentName: c.opponent ? c.opponent.name : 'غير محدد',
        court: c.court || 'غير محدد',
        circuit: c.circuit || 'غير محدد',
        type: c.type,
        date: fileDate,
        time: '09:00',
        subject: `جلسة مستخرجة ومزامنة تلقائياً من مستند: ${file.name}`,
        status: 'pending',
        assignedLawyerId: c.assignedLawyerId || undefined,
        assignedLawyerName,
        notes: `تم رصد الجلسة وإضافتها تلقائياً بناءً على الملف: ${file.name}`
      });
    });
  }

  // 2. Expert sessions scan
  if ((c.isReferredToExperts || c.expertReferral?.isReferred) && c.expertReferral) {
    // 2.1 First session date if specified AND not already included in sessions array
    const hasFirstInSessions = c.expertReferral.firstSessionDate && c.expertReferral.sessions?.some(s => s.date === c.expertReferral?.firstSessionDate);
    if (c.expertReferral.firstSessionDate && !hasFirstInSessions) {
      const firstSessId = `session-expert-first-${c.id}`;
      result.push({
        id: firstSessId,
        caseId: c.id,
        caseNumber: c.caseNumberFirstInstance,
        caseYear: c.caseYearFirstInstance,
        clientName: c.clientName,
        opponentName: c.opponent?.name || 'غير محدد',
        court: c.expertReferral.expertOffice || c.court || 'مكتب خبراء وزارة العدل',
        circuit: c.expertReferral.courtOrCircuit || 'جلسة خبراء أولى',
        type: c.type,
        date: c.expertReferral.firstSessionDate,
        time: '10:00',
        subject: `جلسة خبراء أولى - ${c.expertReferral.expertOffice || 'مكتب الخبراء'} (الخبير: ${c.expertReferral.expertName || 'غير محدد'})`,
        status: 'pending',
        decision: undefined,
        assignedLawyerId: c.assignedLawyerId || undefined,
        assignedLawyerName,
        notes: `جلسة إحالة للخبراء الأولى محددة بالقضية. ${c.expertReferral.referralReason || ''}`,
        isExpertSession: true,
        expertSessionId: 'first-session'
      });
    }

    // 2.2 Sessions array
    if (c.expertReferral.sessions && c.expertReferral.sessions.length > 0) {
      c.expertReferral.sessions.forEach((expSess, idx) => {
        if (expSess.date) {
          const expKey = expSess.id || `exp-${idx}`;
          const sessionId = `session-expert-${c.id}-${expKey}`;
          const hasRealDecision = !!expSess.decisionOrAction && expSess.decisionOrAction.trim() !== '';
          const effectiveStatus = expSess.status === 'pending'
            ? 'pending'
            : expSess.status === 'postponed'
            ? 'postponed'
            : (hasRealDecision || expSess.status === 'completed')
            ? 'completed'
            : 'pending';

          result.push({
            id: sessionId,
            caseId: c.id,
            caseNumber: c.caseNumberFirstInstance,
            caseYear: c.caseYearFirstInstance,
            clientName: c.clientName,
            opponentName: c.opponent?.name || 'غير محدد',
            court: c.expertReferral?.expertOffice || c.court || 'مكتب خبراء وزارة العدل',
            circuit: expSess.location || 'جلسة خبراء',
            type: c.type,
            date: expSess.date,
            time: expSess.time || '10:00',
            subject: `جلسة خبرة (${expSess.sessionType || 'حضور الخبير'}) - ${expSess.location || c.expertReferral?.expertOffice || 'مكتب الخبراء'}`,
            status: effectiveStatus,
            decision: hasRealDecision ? expSess.decisionOrAction : undefined,
            assignedLawyerId: c.assignedLawyerId || undefined,
            assignedLawyerName,
            notes: expSess.notes || 'جلسة خبراء مسجلة في ملف القضية.',
            isExpertSession: true,
            expertSessionId: expKey
          });
        }

        // Next session date if set and distinct from current session date and not already an explicit session item
        if (expSess.nextSessionDate && expSess.nextSessionDate !== expSess.date) {
          const hasNextInArray = c.expertReferral?.sessions?.some(s => s.date === expSess.nextSessionDate);
          if (!hasNextInArray) {
            const nextKey = `session-expert-next-${c.id}-${expSess.id || idx}`;
            result.push({
              id: nextKey,
              caseId: c.id,
              caseNumber: c.caseNumberFirstInstance,
              caseYear: c.caseYearFirstInstance,
              clientName: c.clientName,
              opponentName: c.opponent?.name || 'غير محدد',
              court: c.expertReferral?.expertOffice || 'مكتب خبراء وزارة العدل',
              circuit: expSess.location || c.expertReferral?.courtOrCircuit || 'جلسة مباشرة الخبير',
              type: c.type,
              date: expSess.nextSessionDate,
              time: '10:00',
              subject: `جلسة خبرة ومباشرة قادمة (${expSess.sessionType || 'متابعة'}) - ${expSess.location || c.expertReferral?.expertOffice || 'مكتب الخبراء'}`,
              status: 'pending',
              decision: undefined,
              assignedLawyerId: c.assignedLawyerId || undefined,
              assignedLawyerName,
              notes: `جلسة خبراء مؤجلة بناءً على قرار الجلسة السابقة: ${expSess.decisionOrAction || ''}`,
              isExpertSession: true,
              expertSessionId: `next-${expSess.id || idx}`
            });
          }
        }
      });
    }
  }

  // 3. Detention Renewals scan (سجل تجديدات الحبس الاحتياطي)
  if ((c.isInvestigationActive || (c.detentionRenewals && c.detentionRenewals.length > 0)) && c.detentionRenewals && c.detentionRenewals.length > 0) {
    c.detentionRenewals.forEach((ren, idx) => {
      const renKey = ren.id || `ren-${idx}`;
      const renDate = ren.date || ren.renewalDate;

      // Check if both dates exist and are different, and that nextRenewalDate isn't already covered by another explicit renewal record
      const isNextDateCovered = c.detentionRenewals!.some(r => (r.id !== renKey) && ((r.date || r.renewalDate) === ren.nextRenewalDate));
      const hasDistinctNextDate = !!(ren.nextRenewalDate && renDate && ren.nextRenewalDate !== renDate && !isNextDateCovered);
      const effectiveDate = renDate || ren.nextRenewalDate;

      // A. Upcoming detention renewal session (when distinct next date exists)
      if (hasDistinctNextDate && ren.nextRenewalDate) {
        const nextSessionId = `session-detention-next-${c.id}-${renKey}`;
        result.push({
          id: nextSessionId,
          caseId: c.id,
          caseNumber: c.investigationNumber ? `${c.investigationNumber}/${c.investigationYear || c.caseYearFirstInstance}` : c.caseNumberFirstInstance,
          caseYear: c.investigationYear || c.caseYearFirstInstance,
          clientName: c.clientName,
          opponentName: c.investigationAuthority || (c.opponent?.name || 'النيابة العامة'),
          court: ren.court || ren.nextAuthority || ren.authority || c.investigationAuthority || c.court || 'النيابة العامة / غرفة المشورة',
          circuit: ren.circuit || c.circuit || 'دائرة تجديد الحبس',
          type: c.type || 'جنح',
          date: ren.nextRenewalDate,
          time: '09:00',
          subject: `جلسة تجديد حبس احتياطي (${ren.nextAuthority || ren.authority || 'جهة التجديد'})`,
          status: 'pending',
          assignedLawyerId: c.assignedLawyerId || undefined,
          assignedLawyerName,
          notes: `جلسة تجديد حبس احتياطي قادمة للمتهم/الموكل: ${c.clientName}. ${ren.notes || ''}`,
          isDetentionRenewal: true,
          detentionStartDate: ren.detentionStartDate || c.detentionStartDate,
          detentionAuthority: ren.nextAuthority || ren.authority,
          detentionNextAuthority: ren.nextAuthority,
          detentionDurationDays: ren.durationDays,
          detentionDuration: ren.duration || (ren.durationDays ? `${ren.durationDays} يوم` : undefined),
          detentionRenewalNumber: ren.renewalNumber ? (Number(ren.renewalNumber) + 1) : (idx + 2),
          detentionRenewalId: renKey
        });
      }

      // B. Primary / Recorded renewal session date
      if (effectiveDate) {
        const renSessionId = `session-detention-prev-${c.id}-${renKey}`;
        const hasDecision = !!ren.decision && ren.decision.trim() !== '';
        result.push({
          id: renSessionId,
          caseId: c.id,
          caseNumber: c.investigationNumber ? `${c.investigationNumber}/${c.investigationYear || c.caseYearFirstInstance}` : c.caseNumberFirstInstance,
          caseYear: c.investigationYear || c.caseYearFirstInstance,
          clientName: c.clientName,
          opponentName: c.investigationAuthority || (c.opponent?.name || 'النيابة العامة'),
          court: ren.court || ren.authority || c.investigationAuthority || c.court || 'النيابة العامة',
          circuit: ren.circuit || c.circuit || 'دائرة تجديد الحبس',
          type: c.type || 'جنح',
          date: effectiveDate,
          time: '09:00',
          subject: `جلسة تجديد حبس احتياطي (${ren.authority || 'النيابة العامة'})`,
          status: hasDecision ? 'completed' : 'pending',
          decision: hasDecision ? ren.decision : undefined,
          nextHearingDate: (ren.nextRenewalDate && ren.nextRenewalDate !== effectiveDate) ? ren.nextRenewalDate : undefined,
          assignedLawyerId: c.assignedLawyerId || undefined,
          assignedLawyerName,
          notes: `جلسة تجديد حبس احتياطي مسجلة في ملف القضية. ${ren.notes || ''}`,
          isDetentionRenewal: true,
          detentionStartDate: ren.detentionStartDate || c.detentionStartDate,
          detentionAuthority: ren.authority,
          detentionNextAuthority: ren.nextAuthority,
          detentionDurationDays: ren.durationDays,
          detentionDuration: ren.duration || (ren.durationDays ? `${ren.durationDays} يوم` : undefined),
          detentionRenewalNumber: ren.renewalNumber || (idx + 1),
          detentionDecisionNumber: ren.decisionNumber,
          detentionRenewalId: renKey
        });
      }
    });
  }

  // 4. Investigation Procedures scan (سجل إجراءات التحقيق بالنيابة - يتم إنشاؤها فقط عند تفعيل مرحلة التحقيق)
  if (c.isInvestigationActive && c.investigationProcedures && c.investigationProcedures.length > 0) {
    c.investigationProcedures.forEach((proc, idx) => {
      if (proc.sessionDate) {
        const isDetention = (proc.actionType || '').includes('تجديد') || (proc.actionType || '').includes('حبس') || (proc.actionType || '').includes('استئناف أمر الحبس') || (proc.actionType || '').includes('تحقيق');
        const procKey = proc.id || `proc-${idx}`;
        const procSessionId = `session-proc-${c.id}-${procKey}`;
        result.push({
          id: procSessionId,
          caseId: c.id,
          caseNumber: c.investigationNumber ? `${c.investigationNumber}/${c.investigationYear || c.caseYearFirstInstance}` : c.caseNumberFirstInstance,
          caseYear: c.investigationYear || c.caseYearFirstInstance,
          clientName: c.clientName,
          opponentName: proc.authority || c.investigationAuthority || 'النيابة العامة',
          court: proc.authority || c.court || 'النيابة العامة',
          circuit: c.circuit || 'غرفة المشورة / التحقيق',
          type: c.type || 'جنائي',
          date: proc.sessionDate,
          time: '09:00',
          subject: `جلسة ${proc.actionType || 'تجديد حبس احتياطي'} - ${proc.authority || 'النيابة العامة'}`,
          status: proc.decision ? 'completed' : 'pending',
          decision: proc.decision,
          assignedLawyerId: c.assignedLawyerId || undefined,
          assignedLawyerName,
          notes: `إجراء تحقيق وتجديد حبس مسجل بملف التحقيقات. ${proc.notes || ''}`,
          isDetentionRenewal: isDetention,
          detentionAuthority: proc.authority,
          detentionDurationDays: proc.renewalDays || 15
        });
      }
    });
  }

  return result;
}

/**
 * Extracts all expected automated hearing sessions from all active cases.
 */
export function generateExpectedAutoSessionsForAllCases(cases: Case[], users: any[] = []): Map<string, HearingSession> {
  const map = new Map<string, HearingSession>();
  if (!cases || cases.length === 0) return map;

  cases.forEach(c => {
    const sessions = generateExpectedAutoSessionsForCase(c, users);
    sessions.forEach(sess => {
      map.set(sess.id, sess);
    });
  });

  return map;
}

/**
 * Checks if a file name or category suggests it relates to a court hearing session.
 */
export function checkIfRelatesToHearing(fileName: string, fileCategory: string): boolean {
  const lowerFileName = (fileName || '').toLowerCase();
  
  // Keywords indicating hearing
  const hearingKeywords = [
    'جلسة', 'جلسه', 'حضور', 'رول', 'محضر', 'مرافعة', 
    'مرافعه', 'مذكرة', 'مذكره', 'دفاع', 'حكم', 'قرار', 'تأجيل', 'أجندة', 'اجندة'
  ];
  
  const hasKeyword = hearingKeywords.some(kw => lowerFileName.includes(kw));
  const isHearingCategory = fileCategory ? ['صحف الدعاوى', 'مذكرات', 'أحكام'].includes(fileCategory) : false;
  
  return hasKeyword || isHearingCategory;
}

/**
 * Generates a pre-filled suggestion for a hearing session based on the file metadata.
 */
export function suggestHearingSession(
  fileName: string, 
  fileCategory: string, 
  currentCase: Case
): {
  isSuggested: boolean;
  session: Omit<HearingSession, 'id'>;
} {
  const isSuggested = checkIfRelatesToHearing(fileName, fileCategory);
  const today = new Date();
  const localDateStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;
  const detectedDate = extractHearingDate(fileName) || currentCase.nextHearingDate || localDateStr;
  
  // Build a nice subject
  let subject = '';
  if (fileCategory === 'أحكام') {
    subject = `جلسة النطق بالحكم / استلام منطوق الحكم: ${fileName}`;
  } else if (fileCategory === 'مذكرات') {
    subject = `جلسة تقديم مذكرة الدفاع: ${fileName}`;
  } else if (fileCategory === 'صحف الدعاوى') {
    subject = `جلسة تقديم صحيفة الدعوى / إعلان العريضة: ${fileName}`;
  } else {
    subject = `جلسة متابعة مستندات: ${fileName}`;
  }

  return {
    isSuggested,
    session: {
      caseId: currentCase.id,
      caseNumber: currentCase.caseNumberFirstInstance,
      caseYear: currentCase.caseYearFirstInstance,
      clientName: currentCase.clientName,
      opponentName: currentCase.opponent.name,
      court: currentCase.court,
      circuit: currentCase.circuit,
      type: currentCase.type,
      date: detectedDate,
      time: '09:00',
      subject: subject,
      status: 'pending',
      assignedLawyerId: currentCase.assignedLawyerId,
      notes: `تمت جدولة هذه الجلسة تلقائياً ومزامنتها بناءً على إرفاق ملف: ${fileName} المصنف كـ (${fileCategory})`
    }
  };
}
